version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  build:
    working_directory: ~/BookManagementApplication
    docker:
      - image: cimg/node:18.20.7
    steps:
      - checkout
      - run:
          name: Update npm version
          command: npm install -g npm@10.8.2
      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Install frontend dependencies
          command: cd frontend && npm install --legacy-peer-deps
      - run:
          name: Test frontend
          command: cd frontend && npx jest --passWithNoTests
      - run:
          name: Build React app
          command: cd frontend && npm run build
      - save_cache:
          paths:
            - ~/.npm
          key: dependency-cache-{{ checksum "frontend/package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - frontend/build
            - backend
            - deploy.sh

  deploy:
    docker:
      - image: cimg/node:18.20.7
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Deploy application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS 'rm -rf BookManagementApplication/; git clone https://github.com/LDNP/BookManagementApplication.git; source BookManagementApplication/deploy.sh'