version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/ProjectApplication
    docker:
      - image: cimg/node:18.20.7
    steps:
      - checkout
      - run:
          name: Update npm version
          command: npm install -g npm@10.8.2
      
      # Frontend steps
      - restore_cache:
          key: frontend-dependency-cache-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Install frontend dependencies
          command: cd frontend && npm install --legacy-peer-deps
      - run:
          name: Test frontend
          command: cd frontend && npx jest --passWithNoTests
      - run:
          name: Build React app
          command: cd frontend && npm run build
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-dependency-cache-{{ checksum "frontend/package-lock.json" }}
      
      # Backend steps
      - restore_cache:
          key: backend-dependency-cache-{{ checksum "backend/package-lock.json" }}
      - run:
          name: Install backend dependencies
          command: cd backend && npm install
      - run:
          name: Test backend
          command: cd backend && npx jest
      - save_cache:
          paths:
            - backend/node_modules
          key: backend-dependency-cache-{{ checksum "backend/package-lock.json" }}