version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build 

jobs:
  build:
    working_directory: ~/ProjectApplication
    docker:
      - image: cimg/node:18.20.7
    steps:
      - checkout
      - run:
          name: Update npm version
          command: npm install -g npm@10.8.2
      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Install frontend dependencies
          command: cd frontend && npm install --legacy-peer-deps
      - run:
          name: Build React app
          command: cd frontend && npm run build
      - save_cache:
          paths:
            - ~/.npm
          key: dependency-cache-{{ checksum "frontend/package-lock.json" }}